### PR TITLE
Update visitors report

### PR DESCRIPTION
**Pull request by denys-medynskyi**
### Description

- change PDF styling to black / white: https://cl.ly/bb4c4542a40f
- add link to the visit requests index: https://cl.ly/f3fee73ea84c

### How to test instructions

- Visit http://localhost:3000/admin/events/pivorak-40-back-to-school-edition/visit_requests
- Download report

### CODE REVIEW

**Review by sveredyuk — APPROVED** [review]
Well done, but codeclimate does not like it ;)

**Comment by denys-medynskyi** [comment]
@sveredyuk true, I so get used to rubocop autofix feature :)

**Comment by denys-medynskyi** [comment]
@sveredyuk will be fixed

**Review by sveredyuk — APPROVED** [review]

**Comment by bogdanvlviv** [comment]
:eyes: CI is being broken, seems like related to this change: https://travis-ci.org/pivorakmeetup/pivorak-web-app/builds/581243626#L3802

**Comment by sveredyuk** [comment]
@denysmedynskyi Why you merged red ci build?

**Pull request merged**
