### PR TITLE
#53 Require first_name & last_name during registration

### PR DESCRIPTION
**Pull request by denys-medynskyi**

### CODE REVIEW

**Review by sveredyuk — APPROVED** [review]

**Comment by sveredyuk** [comment]
@skrypalyk any chance to merge this PR ?

**Comment by denys-medynskyi** [comment]
@sveredyuk thanks for reminding

**Comment by denys-medynskyi** [comment]
@sveredyuk I don't get why `chat` tests started to fail, because there is no changes related to `chat` in my pull request

**Comment by sveredyuk** [comment]
@skrypalyk please try to remove `spec/cassettes` from `.gitignore`

**Comment by denys-medynskyi** [comment]
@sveredyuk removed spec/cassettes from gitignore, regenerated cassettes - still red build

**Comment by sveredyuk** [comment]
@skrypalyk check spec output, seems like i18n missing and slack banned API_KEY again ). Maybe we need mock api calls to SlackAPI

**Comment by denys-medynskyi** [comment]
@sveredyuk yes, but I don't have any changes in `I18n file`. This is why I am surprised.
 ok, I will mock slack API calls

**Pull request merged**
