### PR TITLE
#643 Add report bug button

### PR DESCRIPTION
**Pull request by aYaremchuk**
Resolves [github issue](https://github.com/pivorakmeetup/pivorak-web-app/issues/643)

### Description

Added link into main menu.
In link added also parameter to add label bug, but I think it depends on rights on this repo and it will not work for all and also as I understand template for issue can add only person that has rights.

Before:
screenshot 2018-10-21 20 53 55

Result:
screenshot 2018-10-21 20 55 41

### CODE REVIEW

**Review by denys-medynskyi — APPROVED** [review]
👍

**Review by denys-medynskyi — APPROVED** [review]
👍

**Review by denys-medynskyi — APPROVED** [review]
👍

**Review by sveredyuk — COMMENTED** [review]
For 500 We have rollbar. Why we need bug for 422 or 400 ?

**Comment by aYaremchuk** [comment]
@denysmedynskyi @sveredyuk thank you for review. Fixed.

**Pull request merged**
