### PR TITLE
Fix password resend and password confirmation urls

### LINKED ISSUE #252: 'Reset password instructions' email received 'Change my password' link without href
Yandex mail
```<a class="daria-goto-anchor" target="_blank" rel="noopener noreferrer">Change my password</a>```

### PR DESCRIPTION
**Pull request by SqREL**
That should fix problem by adding scheme to url.
Also string interpolation was replaced with route helper methods

Fixed #252

### CODE REVIEW

**Comment by SqREL** [comment]
i have received mail with link to`x-webdoc://4319BD62-43AB-436A-ACE8-288C04FF2598/pivorak.com/users/password/edit?reset_password_token=sometoken`

Assume that it's because missing scheme, but could be wrong

**Review by sveredyuk — APPROVED** [review]
Big thanks! 👍

**Comment by SqREL** [comment]
i have received mail with link to`x-webdoc://4319BD62-43AB-436A-ACE8-288C04FF2598/pivorak.com/users/password/edit?reset_password_token=sometoken`

Assume that it's because missing scheme, but could be wrong

**Comment by slavikg** [comment]
@SqREL @sveredyuk Fixed for Yandex. Thx.

**Pull request merged**
