### PR TITLE
#39 external mail service - Mailgun

### PR DESCRIPTION
**Pull request by denys-medynskyi**

### CODE REVIEW

**Comment by sveredyuk** [comment]
@skrypalyk  `dotenv` gem allows you to use environmental variables from .env file.

`['MAILGUN_API_KEY']` for `production.rb`

**Comment by denys-medynskyi** [comment]
@sveredyuk changed to ENV variable

**Comment by denys-medynskyi** [comment]
@sveredyuk domain name should be in .env too ?

**Comment by sveredyuk** [comment]
@skrypalyk everything important and secret must be in .env and .env must be under .gitignore

**Comment by denys-medynskyi** [comment]
@sveredyuk done

**Review by sveredyuk — APPROVED** [review]

**Comment by sveredyuk** [comment]
@skrypalyk  Travis require env variable. Send me it in slack, I will add into test env.

**Pull request merged**
